# Generated by Django 2.2.16 on 2021-11-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'The ordinary user'), ('moderator', 'User with content edit privileges'), ('admin', 'Full rights user')], default='user', max_length=10),
        ),
    ]
